GET http://localhost:8011/member/
Accept: application/json

###

POST http://localhost:8010/member/register
Content-Type: application/x-www-form-urlencoded

mobile=13233323333


###

POST http://localhost:8010/member/send-code
Accept: application/json

{
  "mobile": "13000000001"
}
